### ISSUE TITLE
Support `#[borrowme(std)]` container attribute

### ISSUE THREAD

**Issue by jvdwrf** [udoprog/borrowme#5]
First of all I would like to thank you for such an amazing crate!
It's really something that is missing from rust, and this fills the gap perfectly.

Now to my issue: I have a bunch of custom fields, that all have the `#[borrowme(std)]` attribute on it.
It would be great if I could add this attribute on the container, to make it the default borrowing method for all fields.

i.e. something like this:
```rust
#[borrowme]
#[borrowme(std)]
struct Struct<'a> {
    field1: &'a CustomWrapper1,
    field2: &'a CustomWrapper2,
}
```

This would forward #[borrowme(std)] to all fields.

**Comment by udoprog** [comment]
That's a great suggestion!

**Comment by udoprog** [comment]
I've added support for this in #6. Thank you for the suggestion!
